name: Newman Run

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: dlee-dev/API-Postman@main
        with:
          collection: proxima-backup.json
          environment: postman_environment.json
